### ISSUE TITLE
Postgres.app on OS X

### ISSUE THREAD

**Issue by microspino** [begriffs/pg_listen#1]
Playing around with this cute tool i had a small issue building on OS X. Just pointing this here for other **Postgres.app** users. I was unable to compile **pg_listen** with make until i changed:

     CFLAGS = -Wall -Wextra `pkg-config --cflags libpq`

with

    CFLAGS = -Wall -Wextra -I/Applications/Postgres.app/Contents/Versions/9.6/include -llibpq

As you my guess I have Postgres 9.6.

**Comment by begriffs** [comment]
Thanks for the note. What does it say in your terminal if you run:

```bash
pkg-config --cflags libpq
```

(Another alternative is using `pg_config --cflags` and `pg_config --ldflags`, since Postgres.app may put `pg_config` on the system path.)

**Comment by microspino** [comment]
@begriffs 
`pkg-config --cflags libpq` returns nothing on my system (OX X El Captain 10.11.16).

`pg_config --cflags` output is:

```
-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels 
-Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv 
-Wno-unused-command-line-argument  -mmacosx-version-min=10.7
```

and `pg_config --ldflags` output is:

```
-L../../src/common -L/Applications/Postgres.app/Contents/Versions/10/lib 
-L/Applications/Postgres.app/Contents/Versions/10/lib -Wl,-dead_strip_dylibs
```

**Comment by begriffs** [comment]
OK, looks like you can make it build by using `pg_config` in the Makefile then. I'm not going to spend time on this, but feel free to send a pull request if you like.

**Comment by begriffs** [comment]
Just noticed that changing `pkg-config` to `pg_config` in the Makefile might not work with the current Nix build, which installs merely libpqxx and not a full postgres installation.

In any case I'll close this issue as you have provided a workaround for the Postgres app on macOS. Thanks for taking the time to file the issue by the way.
