### ISSUE TITLE
Trouble with Make on Ubuntu 18.04

### ISSUE THREAD

**Issue by WillCMcC** [begriffs/pg_listen#11]
![image](https://user-images.githubusercontent.com/7244885/94234788-36cf8600-febf-11ea-8fbd-2a3d67f96b13.png)

I'm unable to get past this error in the make process. It seems like an issue on my end -- if you have any insight it would be much appreciated. I'm running Ubuntu 18.04 and have docker containers with several children including Postgres running.

Thank you!

**Comment by WillCMcC** [comment]
I'm getting some different errors now that lead me to believe this will likely only happen for me (I think because I followed some bad advice regarding linking directories). I'm going to close this issue and ask the question in a more appropriate venue.

**Comment by begriffs** [comment]
I notice in your screenshot it can't find the pkg-config utility. Try `sudo apt-get install pkg-config` and then building the project again.
