### ISSUE TITLE
Allowing clean build with C++ compiler

### ISSUE THREAD

**Issue by begriffs** [begriffs/pg_listen#4]
@EsipovPA I noticed you forked the project and made changes so you could compile with C++. I simplified the code so that it now builds with C89 (acc8cbad47e892cce5bf00cfe5399844977eaf22), can you check whether this code also works with your C++ compiler?

**Comment by begriffs** [comment]
Assuming no response is a good response...

**Comment by EsipovPA** [comment]
I apologize, I did not see this issue. I'll try to check the new version in a day or two

**Comment by EsipovPA** [comment]
At the moment, I did not find any problems while building the project.
