### ISSUE TITLE
How to consume the NOTIFY payload?

### ISSUE THREAD

**Issue by steve-chavez** [begriffs/pg_listen#5]
I'd like to use a script that consumes the NOTIFY input. E.g. the json in:

```sql
NOTIFY 'foo_events', '{"userid":42,"action":"grok"}'
```

Is it possible to do that now?

**Comment by begriffs** [comment]
> I'd like to use a script that consumes the NOTIFY input. … Is it
> possible to do that now?

That's a very reasonable request! Unfortunately pg_listen doesn't
support it yet. We spawn the command using the system() function
provided by the C standard library:

    PQconsumeInput(conn);
    while ((notify = PQnotifies(conn)) != NULL)
    {
      pid = fork();
      if (pid == 0)
        exit(system(cmd));

      PQfreemem(notify);
    }

We could instead use a function from the exec* family [0] of POSIX to
make the call and send the notify payload as stdin or a command line
argument to the executed command. As an extra benefit, the SEI CERT C
Coding Standard advises (in rule ENV33-C [1]) to avoid the system() call
for security reasons.

We can obtain the payload from the return value of PQnotifies. [2]

Would you prefer the payload to be fed to stdin of the new process, or
passed as a command line argument?

0: http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html
1: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177
2: https://www.postgresql.org/docs/current/libpq-notify.html

**Comment by steve-chavez** [comment]
I think payload as argument is more ergonomic. My intention is to use a bash script and it's easier to do `echo $1` than `read var; echo $var`.

**Comment by begriffs** [comment]
> I think payload as argument is more ergonomic.

Makes sense. My only concern is that command line arguments aren't
guaranteed to be able to hold an entire NOTIFY payload. POSIX says:

  The number of bytes available for the new process' combined argument
  and environment lists is {ARG_MAX}. It is implementation-defined
  whether null terminators, pointers, and/or any alignment bytes are
  included in this total.

On my Mac it's defined as 4096. This can be shorter than the payload
limit allowed by the NOTIFY command:

  The "payload" string to be communicated along with the notification
  must be specified as a simple string literal. In the default
  configuration it must be shorter than 8000 bytes. (If binary data or
  large amounts of information need to be communicated, it's best to put
  it in a database table and send the key of the record.)

Do we just go with it and issue a warning if the payload exceeds
ARG_MAX? Or do we choose the safe but sometimes more awkward route of
sending the data through stdin?

**Comment by steve-chavez** [comment]
Oh, I didn't know about that limitation. On Linux/NixOS I get an ARG_MAX of `2097152`.

In that case I agree with playing it safe with stdin. An example of how to read the value could be added on the README.
